CREATE TABLE IF NOT EXISTS zones(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	zone VARCHAR(20) NOT NULL, 
	parent VARCHAR(20) NULL, 
	available BOOLEAN NOT NULL); 
	
CREATE TABLE IF NOT EXISTS requests(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	user_id INT NOT NULL, 
	zone_id INT NOT NULL CONSTRAINT FK_request_zone REFERENCES zones(id)); 
	
CREATE TABLE IF NOT EXISTS requestsCache(
    timezone VARCHAR(50) PRIMARY KEY,
    time_at_timezone TIMESTAMP, 
    time_request TIMESTAMP); 
	
CREATE TABLE IF NOT EXISTS logs (
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	description VARCHAR(50) NULL, 
	exception VARCHAR); 